### ISSUE TITLE
 Dequeued v4l2 buffer contains corrupted data (0 bytes).

### ISSUE THREAD

**Issue by ghost** [slightech/MYNT-EYE-SDK#7]
when runngin ./sample/bin/camera 

 Dequeued v4l2 buffer contains corrupted data (0 bytes).

what is this??

**Comment by takuhara** [comment]
Dequeued v4l2 buffer contains 656448 bytes, but 721920 were expected. Flags: 0x00012005.

**Comment by takuhara** [comment]
I noticed that this phenomenon occurs only when using a USB 3.0 extension cable.
Have you ever used a USB 3.0 extension cable?

**Comment by joinAero** [comment]
Please ensure use USB 3.0 port and run with correct device index, e.g. `./sample/bin/camera 1`

> You could run `<sdk>/tools/list_devices` in the Terminal to see the indexes. See "<sdk>/samples/README.md" to learn more.

About "corrupted data (0 bytes)", FFMpeg prints this information because that V4L2/the driver isn't clearing up properly after the capture.

* [Code - FFmepg/v4l2.c](https://github.com/FFmpeg/FFmpeg/blob/master/libavdevice/v4l2.c), search "Dequeued v4l2 buffer contains corrupted data"
* [Issue - Dequeued v4l2 buffer contains corrupted data (0 bytes)](https://trac.ffmpeg.org/ticket/4988)
* [Patch - uvcvideo error on second capture from USB device, leading to V4L2_BUF_FLAG_ERROR](https://patchwork.linuxtv.org/patch/37010/)

However, our SDK did not depend on FFMpeg on Linux since 1.6.
